comment_prefix = "<!--"
comment_suffix = "-->"

[type_map]
bool = "boolean"
date = "string"
datetime = "string"
decimal = "number"
float = "number"
int = "number"
json = "string"
string = "string"
text = "string"
uuid = "string"
